version: '2'
services:
  postgresql-xtarefas:
    extends:
      file: postgresql.yml
      service: postgresql
    container_name: xtarefas-postgresql
  minio-xtarefas:
    extends:
      file: minio.yml
      service: documentos-minio
    container_name: minio